# Worklog.psm1 - розкладка записів журналу робіт по часу "з - до", перевірки й обмін з Notion.
#
# Потік:
#   1. ConvertFrom-NotionRows - записи, прочитані конектором Notion (MCP), -> робочий JSON
#      або Import-WorklogEntries - те саме з експорту Notion (zip/csv)
#   2. New-WorklogPlan        - план заміни: плейсхолдери задачі -> інтервали для деталізації
#   3. New-WorklogGrid        - план + наявні записи -> сітка слотів "з - до" різної тривалості
#   4. (Claude вписує поле text у кожен слот сітки)
#   5. Test-WorklogEntries    - перевірка текстів і перетинів часу
#   6. New-WorklogNotionOps   - перелік змін для конектора Notion (переписати / створити)
#      або Export-WorklogCsv  - CSV для імпорту в базу Notion (запасний шлях)
#
# Недоторканні записи: FilledInIta = Yes (перенесені в ITA) не змінюються ніколи;
# AutoGenerated = Yes (наша попередня робота) - лише як зайнятий час.
#
# Час - місцевий час користувача, як він записаний у Notion ("Start time" / "End time"): без перерахунку
# поясів. Колонки-формули бази (час з постфіксом "(UKR)", "Hours") модуль не читає й не пише.
# Перетин часу перевіряється так само, як у PLU (WorksPlanning._crossAddWhere): інтервали
# напіввідкриті [з; до), тобто запис, що починається рівно там, де закінчився інший, - не перетин.

Set-StrictMode -Version 2

$script:SkillRoot = Split-Path -Parent $PSScriptRoot
$script:Invariant = [System.Globalization.CultureInfo]::InvariantCulture


#region Конфігурація

function Get-WorklogConfig
{
	<#
	.SYNOPSIS
	Налаштування скіла: config.json скіла, перекритий %USERPROFILE%\.claude\worklog\config.json (якщо є).
	#>
	$config = Get-Content -Raw -Encoding UTF8 -Path (Join-Path $script:SkillRoot 'config.json') | ConvertFrom-Json

	$userPath = Join-Path $env:USERPROFILE '.claude\worklog\config.json'
	if (Test-Path $userPath)
	{
		$user = Get-Content -Raw -Encoding UTF8 -Path $userPath | ConvertFrom-Json
		foreach ($property in $user.PSObject.Properties)
		{
			$config | Add-Member -NotePropertyName $property.Name -NotePropertyValue $property.Value -Force
		}
	}

	$config.workDir = [Environment]::ExpandEnvironmentVariables($config.workDir)
	$config.stopWordsPath = [Environment]::ExpandEnvironmentVariables($config.stopWordsPath)
	if (-not (Test-Path $config.workDir))
	{
		New-Item -ItemType Directory -Path $config.workDir -Force | Out-Null
	}

	return $config
}

#endregion


#region Час і дати

function ConvertTo-WorklogMinutes([string]$Time)
{
	if ($Time -notmatch '^\s*(\d{1,2})[:.](\d{2})\s*$')
	{
		throw "Некоректний час '$Time' - очікується ГГ:ХХ"
	}
	return [int]$Matches[1] * 60 + [int]$Matches[2]
}


function ConvertTo-WorklogTime([int]$Minutes)
{
	return '{0:00}:{1:00}' -f [math]::Floor($Minutes / 60), ($Minutes % 60)
}


function ConvertTo-WorklogHours([int]$Minutes)
{
	return [math]::Round($Minutes / 60, 2)
}


function ConvertTo-WorklogDate([string]$Text)
{
	<#
	.SYNOPSIS
	Дата: ISO, dd.MM.yyyy, dd/MM/yyyy або англійський формат Notion ("September 18, 2026").
	#>
	$value = $Text.Trim()
	$formats = 'yyyy-MM-dd', 'dd.MM.yyyy', 'd.M.yyyy', 'dd/MM/yyyy', 'd/M/yyyy', 'MMMM d, yyyy', 'MMM d, yyyy'
	$result = [datetime]::MinValue
	if ([datetime]::TryParseExact($value, [string[]]$formats, $script:Invariant, 'None', [ref]$result))
	{
		return $result.Date
	}
	throw "Некоректна дата '$Text'"
}


$script:NotionDateTimeFormats = 'dd/MM/yyyy H:mm', 'd/M/yyyy H:mm', 'MMMM d, yyyy h:mm tt', 'MMM d, yyyy h:mm tt',
	'yyyy-MM-dd HH:mm', 'yyyy-MM-ddTHH:mm:ss', 'yyyy-MM-ddTHH:mm', 'yyyy/MM/dd HH:mm', 'dd.MM.yyyy HH:mm'


function ConvertFrom-NotionDateTime([string]$Text)
{
	<#
	.SYNOPSIS
	Дата-час Notion ("18/09/2026 9:00 (GMT+2)", "September 18, 2026 5:20 PM") -> місцевий час.
	.DESCRIPTION
	Дата-час у Notion записується в місцевому часі користувача, тому пояс "(GMT+N)" лише
	відкидається - час не перераховується.
	#>
	$value = [regex]::Replace($Text, '\(GMT[^)]*\)', '').Trim()
	# діапазон "початок → кінець" в одній клітинці - беремо початок
	$value = ($value -split '→')[0].Trim()

	$parsed = [datetime]::MinValue
	if (-not [datetime]::TryParseExact($value, [string[]]$script:NotionDateTimeFormats, $script:Invariant, 'None', [ref]$parsed))
	{
		throw "Некоректна дата-час Notion '$Text'"
	}
	return $parsed
}


function ConvertTo-NotionDateTime([datetime]$Date, [int]$Minutes, [string]$Format)
{
	<#
	.SYNOPSIS
	Місцевий час -> текст дати-часу для імпорту в Notion (формат config.notion.dateTimeFormat).
	#>
	return $Date.Date.AddMinutes($Minutes).ToString($Format, $script:Invariant)
}

#endregion


#region Читання записів

function Import-WorklogEntries
{
	<#
	.SYNOPSIS
	Прочитати записи журналу: експорт Notion (zip або csv) чи JSON сітки.
	.DESCRIPTION
	zip - шукається CSV бази (найбільший "*_all.csv", інакше найбільший csv).
	CSV Notion - колонки з config.notion.columns; дата-час із колонок start / end - це і є
	робочий час (колонки-формули не читаються).
	JSON - масив об'єктів з полями date, from, to, text, task.
	.PARAMETER TaskCode
	Лишити тільки записи задачі (код у квадратних дужках назви задачі, напр. 1727840).
	#>
	param(
		[Parameter(Mandatory)] [string]$Path,
		[string]$TaskCode
	)

	$config = Get-WorklogConfig
	$result = New-Object System.Collections.Generic.List[object]

	if ($Path -like '*.zip')
	{
		$Path = Get-NotionCsvFromZip -Path $Path -Config $config
	}

	if ($Path -like '*.json')
	{
		foreach ($row in (Read-WorklogJson $Path))
		{
			# JSON - робочі файли скіла, тож без поля auto запис вважається згенерованим
			$auto = (Get-OptionalValue $row 'auto') -ne 'False'
			$result.Add((New-WorklogEntry -Date (ConvertTo-WorklogDate $row.date) `
				-Start (ConvertTo-WorklogMinutes $row.from) -End (ConvertTo-WorklogMinutes $row.to) `
				-Text (Get-OptionalValue $row 'text') -Task (Get-OptionalValue $row 'task') -Auto $auto `
				-Page (Get-OptionalValue $row 'page') -Filled ((Get-OptionalValue $row 'filled') -eq 'True') `
				-TaskPage (Get-OptionalValue $row 'taskPage')))
		}
	}
	else
	{
		$columns = $config.notion.columns
		foreach ($row in (Import-Csv -LiteralPath $Path -Encoding UTF8))
		{
			$startCell = Get-OptionalValue $row $columns.start
			$endCell = Get-OptionalValue $row $columns.end
			if ([string]::IsNullOrWhiteSpace($startCell) -or [string]::IsNullOrWhiteSpace($endCell))
			{
				Write-Warning ("Запис без часу пропущено: {0}" -f (Get-OptionalValue $row $columns.text))
				continue
			}

			$start = ConvertFrom-NotionDateTime $startCell
			$end = ConvertFrom-NotionDateTime $endCell
			$startMinutes = [int]$start.TimeOfDay.TotalMinutes
			$endMinutes = [int]($end - $start.Date).TotalMinutes

			$result.Add((New-WorklogEntry -Date $start.Date -Start $startMinutes -End $endMinutes `
				-Text (Get-OptionalValue $row $columns.text).Trim() `
				-Task (Get-NotionPageTitle (Get-OptionalValue $row $columns.task)) `
				-Auto ((Get-OptionalValue $row $columns.autoGenerated) -eq $config.notion.yesValue)))
		}
	}

	if ($TaskCode)
	{
		return @($result | Where-Object { $_.task -like "*[[]$TaskCode[]]*" -or $_.task -eq $TaskCode })
	}
	return $result
}


function Get-NotionCsvFromZip([string]$Path, $Config)
{
	$target = Join-Path $Config.workDir ('import-' + [System.IO.Path]::GetFileNameWithoutExtension($Path))
	Expand-Archive -LiteralPath $Path -DestinationPath $target -Force

	$csv = Get-ChildItem -Path $target -Recurse -Filter '*_all.csv' | Sort-Object Length -Descending | Select-Object -First 1
	if (-not $csv)
	{
		$csv = Get-ChildItem -Path $target -Recurse -Filter '*.csv' | Sort-Object Length -Descending | Select-Object -First 1
	}
	if (-not $csv)
	{
		throw "В архіві '$Path' немає CSV бази Notion"
	}
	return $csv.FullName
}


function Get-NotionPageTitle([string]$Cell)
{
	<#
	.SYNOPSIS
	Назва сторінки зі зв'язку Notion: "[1727840] Назва (https://www.notion.so/...)" -> "[1727840] Назва".
	.DESCRIPTION
	Посилання буває повним URL або відносним шляхом до .md у zip-експорті - в обох немає пробілів
	(шлях закодовано), тому відрізається останнє "(...)" без пробілів усередині.
	#>
	return ($Cell -replace '\s*\([^\s)]*\)\s*$', '').Trim()
}


function Get-WorklogFileName([string]$Title, [string]$Suffix, $Config)
{
	<#
	.SYNOPSIS
	Шлях робочого файлу, названого за назвою задачі: "[1727840] Назва" -> "1727840 Назва<Suffix>".
	.DESCRIPTION
	Квадратні дужки прибираються: у PowerShell вони - символи шаблону шляху і ламають -Path.
	#>
	$name = $Title -replace '[\[\]]', '' -replace '[\\/:*?"<>|]', ' ' -replace '\s+', ' '
	return Join-Path $Config.workDir ($name.Trim() + $Suffix)
}


function Read-WorklogJson([string]$Path)
{
	# у PowerShell 5.1 ConvertFrom-Json віддає масив одним об'єктом - розгортаємо в елементи
	$data = Get-Content -Raw -Encoding UTF8 -LiteralPath $Path | ConvertFrom-Json
	return @($data | ForEach-Object { $_ })
}


function Get-OptionalValue($Object, [string]$Name)
{
	$property = $Object.PSObject.Properties[$Name]
	if ($null -eq $property -or $null -eq $property.Value)
	{
		return ''
	}
	return [string]$property.Value
}


function New-WorklogEntry([datetime]$Date, [int]$Start, [int]$End, [string]$Text = '', [string]$Task = '', [bool]$Auto = $true,
	[string]$Page = '', [bool]$Filled = $false, [string]$TaskPage = '')
{
	# auto   - запис згенеровано скілом (колонка AutoGenerated у Notion); записи, внесені
	#          користувачем вручну, мають auto = false
	# filled - запис уже перенесено в ITA (FilledInIta): чіпати його не можна ніколи
	# page   - сторінка запису в Notion; заповнене тільки для записів, прочитаних через MCP,
	#          і саме воно дозволяє редагувати запис на місці замість імпорту CSV
	return [pscustomobject]@{
		date     = $Date.ToString('yyyy-MM-dd', $script:Invariant)
		from     = ConvertTo-WorklogTime $Start
		to       = ConvertTo-WorklogTime $End
		hours    = ConvertTo-WorklogHours ($End - $Start)
		task     = $Task
		auto     = $Auto
		filled   = $Filled
		page     = $Page
		taskPage = $TaskPage
		text     = $Text
	}
}

#endregion


#region Notion через MCP

function ConvertFrom-NotionRows
{
	<#
	.SYNOPSIS
	Рядки, прочитані з Timesheet конектором Notion (MCP), -> робочий JSON записів журналу.
	.DESCRIPTION
	Вхід - JSON, збережений із відповіді query_data_sources: або сам масив рядків, або обгортка
	з полем results. Очікувані псевдоніми колонок запиту: page, start, finish, auto, filled,
	task, text (готовий SQL - у SKILL.md).
	Час у відповіді має вигляд "2026-09-24 08:00:00Z". Літера Z тут НЕ означає UTC - це той
	самий місцевий час, що його бачить користувач у Notion, тож пояс не перераховується
	(так само, як відкидається "(GMT+2)" у CSV-експорті).
	.PARAMETER TasksPath
	JSON рядків бази "Task codes" (псевдоніми url, code, name) - щоб зі зв'язку TaskCode
	отримати назву задачі, а не лише посилання: міжбазовий SQL-запит доступний не на всіх тарифах.
	#>
	param(
		[Parameter(Mandatory)] [string]$Path,
		[string]$TasksPath,
		[string]$OutPath
	)

	$config = Get-WorklogConfig
	$rows = Get-NotionRowArray $Path
	$titles = @{}
	if ($TasksPath)
	{
		foreach ($task in (Get-NotionRowArray $TasksPath))
		{
			$url = Get-OptionalValue $task 'url'
			if ($url)
			{
				$titles[(Get-NotionPageId $url)] = Get-OptionalValue $task 'name'
			}
		}
	}

	$entries = New-Object System.Collections.Generic.List[object]
	foreach ($row in $rows)
	{
		$startCell = Get-OptionalValue $row 'start'
		$endCell = Get-OptionalValue $row 'finish'
		if (-not $startCell -or -not $endCell)
		{
			Write-Warning ("Запис без часу пропущено: {0}" -f (Get-OptionalValue $row 'text'))
			continue
		}

		$start = ConvertFrom-NotionRowDate $startCell $config
		$end = ConvertFrom-NotionRowDate $endCell $config
		$taskPage = Get-NotionPageId (Get-OptionalValue $row 'task')
		$title = if ($taskPage -and $titles.ContainsKey($taskPage)) { $titles[$taskPage] } else { '' }

		$entries.Add((New-WorklogEntry -Date $start.Date -Start ([int]$start.TimeOfDay.TotalMinutes) `
			-End ([int]($end - $start.Date).TotalMinutes) -Text (Get-OptionalValue $row 'text').Trim() `
			-Task $title -Auto ((Get-OptionalValue $row 'auto') -eq '__YES__') `
			-Page (Get-OptionalValue $row 'page') -Filled ((Get-OptionalValue $row 'filled') -eq '__YES__') `
			-TaskPage $taskPage))
	}

	if (-not $OutPath)
	{
		$OutPath = Join-Path $config.workDir ('журнал {0}.json' -f (Get-Date -Format 'yyyy-MM-dd HH-mm'))
	}
	ConvertTo-Json -InputObject ([object[]]$entries.ToArray()) -Depth 3 | Set-Content -LiteralPath $OutPath -Encoding UTF8

	Write-Output ("Журнал: {0} записів -> {1}" -f $entries.Count, $OutPath)
}


function Get-NotionRowArray([string]$Path)
{
	$data = Get-Content -Raw -Encoding UTF8 -LiteralPath $Path | ConvertFrom-Json
	if ($null -ne $data.PSObject.Properties['results'])
	{
		$data = $data.results
	}
	return @($data | ForEach-Object { $_ })
}


function Get-NotionPageId([string]$Cell)
{
	<#
	.SYNOPSIS
	Ідентифікатор сторінки з посилання або зі зв'язку ["https://app.notion.com/<id>"] - без дефісів.
	#>
	if ($Cell -match '([0-9a-fA-F]{8}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{4}-?[0-9a-fA-F]{12})')
	{
		return ($Matches[1] -replace '-', '').ToLower()
	}
	return ''
}


function Get-WorklogTimeZone($Config)
{
	# пояс журналу: конектор працює в UTC, а користувач (і сам журнал) - у місцевому часі
	return [System.TimeZoneInfo]::FindSystemTimeZoneById($Config.notion.mcpTimeZoneId)
}


function ConvertFrom-NotionRowDate([string]$Text, $Config)
{
	<#
	.SYNOPSIS
	Дата-час із відповіді конектора ("2026-09-24 08:00:00Z") -> місцевий час журналу.
	.DESCRIPTION
	Z тут справжня: конектор віддає UTC, тоді як у Notion і в CSV-експорті той самий запис
	видно в місцевому часі (перевірено 24.09.2026 - різниця рівно на зсув поясу). Переведення
	йде через пояс notion.mcpTimeZoneId, а не через сталу кількість годин: узимку зсув інший.
	#>
	$value = $Text.Trim().TrimEnd('Z').Replace('T', ' ').Trim()
	$formats = 'yyyy-MM-dd HH:mm:ss.fff', 'yyyy-MM-dd HH:mm:ss', 'yyyy-MM-dd HH:mm'
	$utc = [datetime]::ParseExact($value, [string[]]$formats, $script:Invariant, [System.Globalization.DateTimeStyles]::None)
	return [System.TimeZoneInfo]::ConvertTimeFromUtc($utc, (Get-WorklogTimeZone $Config))
}


function ConvertTo-NotionRowDate([datetime]$Local, $Config)
{
	<#
	.SYNOPSIS
	Місцевий час журналу -> рядок для конектора (UTC з літерою Z).
	#>
	$utc = [System.TimeZoneInfo]::ConvertTimeToUtc([datetime]::SpecifyKind($Local, [System.DateTimeKind]::Unspecified), (Get-WorklogTimeZone $Config))
	return $utc.ToString($Config.notion.mcpDateTimeFormat, $script:Invariant)
}


function Test-WorklogPlaceholderText([string]$Text, $Config)
{
	<#
	.SYNOPSIS
	Чи схожий текст запису на плейсхолдер користувача ("New task", "укрпол реімплементація").
	.DESCRIPTION
	Плейсхолдер - це позначка часу без суті: порожній текст, текст із переліку
	notion.placeholderTexts або коротший за notion.placeholderMaxLength символів.
	Ознака нестрога: остаточне рішення приймає користувач, тому Get-WorklogPlaceholders
	показує перелік, а не переписує мовчки.
	#>
	$value = $Text.Trim()
	if (-not $value)
	{
		return $true
	}
	if ($Config.notion.placeholderTexts -contains $value.ToUpper())
	{
		return $true
	}
	return $value.Length -le $Config.notion.placeholderMaxLength
}


function Get-WorklogPlaceholders
{
	<#
	.SYNOPSIS
	Розкласти записи журналу на три групи: недоторканні, згенеровані й плейсхолдери.
	.DESCRIPTION
	kind у видачі:
	  перенесено  - FilledInIta = Yes: запис уже в ITA, не чіпати ніколи й ні за яких ключів;
	  згенеровано - AutoGenerated = Yes: наша попередня робота, лишається як зайнятий час;
	  плейсхолдер - ручний запис без суті: кандидат на заміну;
	  ручний      - ручний запис зі змістовним текстом: сам собою не замінюється.
	#>
	param(
		[Parameter(Mandatory)] [string]$Path,
		[string]$TaskCode
	)

	$config = Get-WorklogConfig
	$entries = @(Import-WorklogEntries -Path $Path -TaskCode $TaskCode | Sort-Object date, from)

	$result = foreach ($entry in $entries)
	{
		$kind = if ($entry.filled) { 'перенесено' }
			elseif ($entry.auto) { 'згенеровано' }
			elseif (Test-WorklogPlaceholderText $entry.text $config) { 'плейсхолдер' }
			else { 'ручний' }
		$entry | Add-Member -NotePropertyName kind -NotePropertyValue $kind -PassThru -Force
	}
	return @($result)
}

#endregion


#region План і сітка

function New-WorklogPlan
{
	<#
	.SYNOPSIS
	План заміни: кожен наявний (загальний) запис задачі стає інтервалом для деталізації.
	.DESCRIPTION
	Беруться лише плейсхолдери користувача - ручні записи без суті (AutoGenerated = No,
	FilledInIta = No). Записи, перенесені в ITA (FilledInIta = Yes), не беруться НІКОЛИ,
	навіть із -IncludeGenerated чи -All: вони вже здані. Згенеровані раніше лишаються
	в журналі як зайнятий час.
	У плані зберігаються page (сторінка плейсхолдера в Notion) і text (його вихідний текст) -
	перше дає змогу відредагувати запис на місці, друге є підказкою, що робилось у цей час.
	.PARAMETER All
	Брати всі ручні записи задачі, а не лише ті, що схожі на плейсхолдери.
	.PARAMETER IncludeGenerated
	Перегенерувати й записи, створені скілом раніше (їх тоді треба видалити в Notion).
	#>
	param(
		[Parameter(Mandatory)] [string]$ExistingPath,
		[Parameter(Mandatory)] [string]$TaskCode,
		[string]$OutPath,
		[switch]$All,
		[switch]$IncludeGenerated
	)

	$config = Get-WorklogConfig
	$entries = @(Get-WorklogPlaceholders -Path $ExistingPath -TaskCode $TaskCode |
		Where-Object { $_.kind -eq 'плейсхолдер' -or ($All -and $_.kind -eq 'ручний') -or ($IncludeGenerated -and $_.kind -eq 'згенеровано') } |
		Sort-Object date, from)
	if (-not $entries)
	{
		throw "У '$ExistingPath' немає плейсхолдерів задачі $TaskCode (спробуйте -All)"
	}

	$plan = @($entries | ForEach-Object {
		[pscustomobject]@{ date = $_.date; from = $_.from; to = $_.to; task = $_.task; taskPage = $_.taskPage; page = $_.page; text = $_.text }
	})
	if (-not $OutPath)
	{
		$title = if ($entries[0].task) { $entries[0].task } else { $TaskCode }
		$OutPath = Get-WorklogFileName $title ' - план.json' $config
	}
	ConvertTo-Json -InputObject ([object[]]$plan) -Depth 3 | Set-Content -LiteralPath $OutPath -Encoding UTF8

	Write-Output ("План: {0} інтервалів, {1} год -> {2}" -f $plan.Count, ($entries | Measure-Object -Property hours -Sum).Sum, $OutPath)
	$plan | Format-Table date, from, to, text -AutoSize -Wrap | Out-String -Width 200
}


function Get-ReplacedKeys($Plan)
{
	<#
	.SYNOPSIS
	Ключі "дата|з|до" загальних записів, які план замінює деталізованими.
	#>
	$keys = @()
	foreach ($day in $Plan)
	{
		if ((Get-OptionalValue $day 'from') -and (Get-OptionalValue $day 'to'))
		{
			$keys += '{0}|{1}|{2}' -f (ConvertTo-WorklogDate $day.date).ToString('yyyy-MM-dd'),
				(ConvertTo-WorklogTime (ConvertTo-WorklogMinutes $day.from)),
				(ConvertTo-WorklogTime (ConvertTo-WorklogMinutes $day.to))
		}
	}
	return $keys
}


function New-WorklogGrid
{
	<#
	.SYNOPSIS
	Розкласти роботу по слотах "з - до" без перетину з наявними записами.
	.PARAMETER PlanPath
	JSON-масив (New-WorklogPlan або вручну). Кожен елемент:
	  { "date": "2026-09-18", "hours": 7.5 }                     - покласти 7.5 год у вільний час дня
	  { "date": "2026-09-18", "hours": 4, "after": "11:00" }      - те саме, але не раніше 11:00
	  { "date": "2026-09-19", "from": "10:00", "to": "18:15" }    - замінити загальний запис цим інтервалом
	Необов'язкове поле task переноситься в усі записи слоту.
	.PARAMETER ExistingPath
	Наявні записи за ці дні (zip/csv Notion або JSON). Запис, чий інтервал точно збігається
	з інтервалом "from/to" плану, вважається загальним і замінюється.
	.PARAMETER Seed
	Зерно випадкового розбиття на тривалості - щоб повторний запуск давав ту саму сітку.
	#>
	param(
		[Parameter(Mandatory)] [string]$PlanPath,
		[string]$ExistingPath,
		[string]$OutPath,
		[int]$Seed = 0
	)

	$config = Get-WorklogConfig
	$rng = if ($Seed -ne 0) { New-Object System.Random $Seed } else { New-Object System.Random }
	$plan = Read-WorklogJson $PlanPath

	$existing = @()
	if ($ExistingPath)
	{
		$existing = @(Import-WorklogEntries -Path $ExistingPath)
	}
	$replaced = @(Get-ReplacedKeys $plan)
	$busy = @($existing | Where-Object { $replaced -notcontains ('{0}|{1}|{2}' -f $_.date, $_.from, $_.to) })

	$slots = New-Object System.Collections.Generic.List[object]
	foreach ($day in $plan)
	{
		$date = ConvertTo-WorklogDate $day.date
		$dayKey = $date.ToString('yyyy-MM-dd')
		$task = Get-OptionalValue $day 'task'
		$dayBusy = @($busy | Where-Object { $_.date -eq $dayKey } | ForEach-Object {
			[pscustomobject]@{ Start = ConvertTo-WorklogMinutes $_.from; End = ConvertTo-WorklogMinutes $_.to }
		})

		if ((Get-OptionalValue $day 'from') -and (Get-OptionalValue $day 'to'))
		{
			# інтервал задано явно (заміна загального запису): перерви не віднімаються -
			# користувач уже зафіксував цей час як робочий
			$start = ConvertTo-WorklogMinutes $day.from
			$end = ConvertTo-WorklogMinutes $day.to
			foreach ($interval in (Get-FreeIntervals -Start $start -End $end -Busy $dayBusy))
			{
				$slots.Add([pscustomobject]@{ Date = $date; Start = $interval.Start; End = $interval.End; Task = $task })
			}
			continue
		}

		$needed = [int][math]::Round([double]$day.hours * 60 / $config.stepMinutes) * $config.stepMinutes
		$after = Get-OptionalValue $day 'after'
		$start = if ($after) { ConvertTo-WorklogMinutes $after } else { ConvertTo-WorklogMinutes $config.dayStart }
		$end = ConvertTo-WorklogMinutes $config.dayEnd

		$dayBreaks = @($config.breaks | ForEach-Object {
			[pscustomobject]@{ Start = ConvertTo-WorklogMinutes $_.from; End = ConvertTo-WorklogMinutes $_.to }
		})
		foreach ($interval in (Get-FreeIntervals -Start $start -End $end -Busy ($dayBusy + $dayBreaks)))
		{
			if ($needed -le 0)
			{
				break
			}
			$length = $interval.End - $interval.Start
			# дрібний проміжок між чужими записами не забираємо, якщо ще лишається багато часу
			if ($length -lt $config.minEntryMinutes -and $needed -gt $length)
			{
				continue
			}
			$take = [math]::Min($length, $needed)
			$slots.Add([pscustomobject]@{ Date = $date; Start = $interval.Start; End = $interval.Start + $take; Task = $task })
			$needed -= $take
		}
		if ($needed -gt 0)
		{
			Write-Warning ("{0}: не вистачило вільного часу до {1} - не розкладено {2} год" -f $dayKey, $config.dayEnd, (ConvertTo-WorklogHours $needed))
		}
	}

	# розбиття слотів на записи різної тривалості
	$used = @{}
	$previous = 0
	$grid = New-Object System.Collections.Generic.List[object]
	foreach ($slot in ($slots | Sort-Object Date, Start))
	{
		$durations = Split-WorklogDuration -Minutes ($slot.End - $slot.Start) -Config $config -Used $used -Previous $previous -Rng $rng
		$cursor = $slot.Start
		foreach ($duration in $durations)
		{
			$grid.Add((New-WorklogEntry -Date $slot.Date -Start $cursor -End ($cursor + $duration) -Task $slot.Task))
			$cursor += $duration
			$previous = $duration
		}
	}

	if (-not $OutPath)
	{
		# одна задача в плані - файл за її назвою (CSV потім отримає ту саму назву)
		$titles = @($grid | ForEach-Object { $_.task } | Where-Object { $_ } | Select-Object -Unique)
		$OutPath = if ($titles.Count -eq 1) {
			Get-WorklogFileName $titles[0] '.json' $config
		} else {
			Join-Path $config.workDir ('записи {0}.json' -f (Get-Date -Format 'yyyy-MM-dd HH-mm'))
		}
	}
	# у PowerShell 5.1 ConvertTo-Json не серіалізує List<object> напряму - лише масив
	ConvertTo-Json -InputObject ([object[]]$grid.ToArray()) -Depth 3 | Set-Content -LiteralPath $OutPath -Encoding UTF8

	$total = ($grid | Measure-Object -Property hours -Sum).Sum
	Write-Output ("Сітка: {0} записів, {1} год -> {2}" -f $grid.Count, $total, $OutPath)
	$grid | Format-Table date, from, to, hours -AutoSize | Out-String -Width 200
}


function Get-FreeIntervals([int]$Start, [int]$End, $Busy)
{
	<#
	.SYNOPSIS
	Вільні проміжки в [Start; End) за вирахуванням зайнятих інтервалів.
	#>
	$result = @()
	$cursor = $Start
	foreach ($interval in (@($Busy) | Where-Object { $_ -and $_.End -gt $Start -and $_.Start -lt $End } | Sort-Object Start))
	{
		if ($interval.Start -gt $cursor)
		{
			$result += [pscustomobject]@{ Start = $cursor; End = $interval.Start }
		}
		if ($interval.End -gt $cursor)
		{
			$cursor = $interval.End
		}
	}
	if ($cursor -lt $End)
	{
		$result += [pscustomobject]@{ Start = $cursor; End = $End }
	}
	return $result
}


function Split-WorklogDuration
{
	<#
	.SYNOPSIS
	Розбити слот на записи: кратно кроку, у межах [min; max], сусідні тривалості різні,
	одна тривалість - не частіше за maxSameDuration на весь список.
	#>
	param(
		[int]$Minutes,
		$Config,
		[hashtable]$Used,
		[int]$Previous,
		[System.Random]$Rng
	)

	$min = [int]$Config.minEntryMinutes
	$max = [int]$Config.maxEntryMinutes
	$step = [int]$Config.stepMinutes
	$maxRepeat = [int]$Config.maxSameDuration

	if ($Minutes -le $max)
	{
		$Used[$Minutes] = 1 + $(if ($Used.ContainsKey($Minutes)) { $Used[$Minutes] } else { 0 })
		return , @($Minutes)
	}

	$countMin = [int][math]::Ceiling($Minutes / $max)
	$countMax = [math]::Max($countMin, [int][math]::Floor($Minutes / $min))
	$countTarget = [math]::Min($countMax, [math]::Max($countMin, [int][math]::Round($Minutes / [double]$Config.targetEntryMinutes)))

	for ($attempt = 0; $attempt -lt 2000; $attempt++)
	{
		$count = if ($attempt -lt 1000) { $countTarget } else { $Rng.Next($countMin, $countMax + 1) }
		$parts = @()
		for ($i = 0; $i -lt $count; $i++)
		{
			$parts += $Rng.Next([int]($min / $step), [int]($max / $step) + 1) * $step
		}

		# підігнати суму під довжину слота кроками по $step
		$diff = $Minutes - ($parts | Measure-Object -Sum).Sum
		$guard = 0
		while ($diff -ne 0 -and $guard -lt 1000)
		{
			$index = $Rng.Next(0, $count)
			$delta = if ($diff -gt 0) { $step } else { -$step }
			$candidate = $parts[$index] + $delta
			if ($candidate -ge $min -and $candidate -le $max)
			{
				$parts[$index] = $candidate
				$diff -= $delta
			}
			$guard++
		}
		if ($diff -ne 0)
		{
			continue
		}

		$valid = $true
		$last = $Previous
		$counts = $Used.Clone()
		foreach ($part in $parts)
		{
			$seen = if ($counts.ContainsKey($part)) { $counts[$part] } else { 0 }
			if ($part -eq $last -or $seen -ge $maxRepeat)
			{
				$valid = $false
				break
			}
			$counts[$part] = $seen + 1
			$last = $part
		}
		if ($valid)
		{
			foreach ($key in $counts.Keys) { $Used[$key] = $counts[$key] }
			return , $parts
		}
	}

	throw "Не вдалося розбити $Minutes хв на записи з урахуванням обмежень - змініть min/max у config.json"
}

#endregion


#region Перевірка

function Test-WorklogEntries
{
	<#
	.SYNOPSIS
	Перевірити заповнену сітку: тексти (довжина, стоп-слова, розділовий знак у кінці, повтори)
	і перетини часу між собою та з наявними записами.
	.PARAMETER PlanPath
	План, за яким будувалась сітка: загальні записи, які він замінює, у перевірці перетину не враховуються.
	#>
	param(
		[Parameter(Mandatory)] [string]$Path,
		[string]$ExistingPath,
		[string]$PlanPath
	)

	$config = Get-WorklogConfig
	$entries = @(Import-WorklogEntries -Path $Path)
	$issues = New-Object System.Collections.Generic.List[string]

	$stopWords = @(Get-WorklogStopWords -Config $config)
	$texts = @{}
	foreach ($entry in $entries)
	{
		$label = '{0} {1}-{2}' -f $entry.date, $entry.from, $entry.to
		$text = $entry.text.Trim()
		$upper = $text.ToUpper()

		if (-not $text)
		{
			$issues.Add("$label - порожній текст")
			continue
		}
		if ($text.Length -gt $config.textLimit)
		{
			$issues.Add("$label - $($text.Length) символів, ліміт $($config.textLimit)")
		}
		if ($text -match '[\.\!\?;:,]$')
		{
			$issues.Add("$label - розділовий знак у кінці")
		}
		foreach ($fragment in $config.forbiddenFragments)
		{
			if ($upper.Contains($fragment))
			{
				$issues.Add("$label - заборонений фрагмент '$($fragment.Trim())'")
			}
		}
		foreach ($word in $stopWords)
		{
			if ($upper.Contains($word.Fragment) -and -not ($word.Exception -and $upper.Contains($word.Exception)))
			{
				$issues.Add("$label - стоп-слово PLU '$($word.Fragment)'")
			}
		}
		if ($texts.ContainsKey($upper))
		{
			$issues.Add("$label - текст повторює запис $($texts[$upper])")
		}
		else
		{
			$texts[$upper] = $label
		}
		if ($entry.hours * 60 -gt $config.maxEntryMinutes + 0.5)
		{
			$issues.Add("$label - тривалість $($entry.hours) год більша за $($config.maxEntryMinutes) хв")
		}
	}

	$all = @($entries | ForEach-Object { $_ | Add-Member -NotePropertyName Source -NotePropertyValue 'новий' -PassThru -Force })
	if ($ExistingPath)
	{
		$replaced = @()
		if ($PlanPath)
		{
			$replaced = @(Get-ReplacedKeys (Read-WorklogJson $PlanPath))
		}
		$all += @(Import-WorklogEntries -Path $ExistingPath |
			Where-Object { $replaced -notcontains ('{0}|{1}|{2}' -f $_.date, $_.from, $_.to) } |
			ForEach-Object { $_ | Add-Member -NotePropertyName Source -NotePropertyValue 'наявний' -PassThru -Force })
	}
	foreach ($group in ($all | Group-Object date))
	{
		$sorted = @($group.Group | Sort-Object { ConvertTo-WorklogMinutes $_.from })
		for ($i = 1; $i -lt $sorted.Count; $i++)
		{
			for ($j = 0; $j -lt $i; $j++)
			{
				$a = $sorted[$j]
				$b = $sorted[$i]
				# [з; до) - як у перевірці перетину PLU
				if ((ConvertTo-WorklogMinutes $b.from) -lt (ConvertTo-WorklogMinutes $a.to) -and ($a.Source -eq 'новий' -or $b.Source -eq 'новий'))
				{
					$issues.Add(('{0}: {1}-{2} ({3}) перетинається з {4}-{5} ({6})' -f $group.Name, $a.from, $a.to, $a.Source, $b.from, $b.to, $b.Source))
				}
			}
		}
	}

	if ($issues.Count -eq 0)
	{
		Write-Output ("OK: {0} записів, {1} год" -f $entries.Count, ($entries | Measure-Object -Property hours -Sum).Sum)
	}
	else
	{
		Write-Output ("Знайдено {0} зауважень:" -f $issues.Count)
		$issues | ForEach-Object { Write-Output "  - $_" }
	}
}


function Get-WorklogStopWords($Config)
{
	<#
	.SYNOPSIS
	Стоп-слова PLU (перевірка WorksPlanning.WorkDescription.Valid): "ФРАГМЕНТ" або "ФРАГМЕНТ | ВИНЯТОК".
	#>
	if (-not (Test-Path $Config.stopWordsPath))
	{
		return @()
	}

	foreach ($line in (Get-Content -Encoding UTF8 -Path $Config.stopWordsPath))
	{
		$value = $line.Trim()
		if (-not $value -or $value.StartsWith('#'))
		{
			continue
		}
		$pair = $value -split '\|'
		[pscustomobject]@{
			Fragment  = $pair[0].Trim().ToUpper()
			Exception = if ($pair.Count -gt 1) { $pair[1].Trim().ToUpper() } else { '' }
		}
	}
}

#endregion


#region Вивід

function Export-WorklogCsv
{
	<#
	.SYNOPSIS
	CSV для імпорту в базу Notion (меню бази "..." -> Merge with CSV).
	.DESCRIPTION
	Пишуться лише колонки, які Notion може прийняти: текст, дата-час початку й кінця
	(місцевий час), зв'язок із задачею (назва сторінки) і прапорець FilledInIta.
	Колонки-формули бази ("Hours", час з постфіксом "(UKR)") не пишуться - Notion порахує їх сам.
	UTF-8 з BOM, щоб кирилицю коректно читали і Notion, і Excel.
	.PARAMETER Task
	Назва сторінки задачі для колонки зв'язку, якщо в записах поле task порожнє.
	#>
	param(
		[Parameter(Mandatory)] [string]$Path,
		[string]$OutPath,
		[string]$Task = ''
	)

	$config = Get-WorklogConfig
	$columns = $config.notion.columns
	$entries = @(Import-WorklogEntries -Path $Path)

	if (-not $OutPath)
	{
		$OutPath = [System.IO.Path]::ChangeExtension($Path, '.csv')
	}

	$rows = foreach ($entry in $entries)
	{
		$date = ConvertTo-WorklogDate $entry.date
		$row = [ordered]@{}
		$row[$columns.text] = $entry.text
		$row[$columns.start] = ConvertTo-NotionDateTime $date (ConvertTo-WorklogMinutes $entry.from) $config.notion.dateTimeFormat
		$row[$columns.end] = ConvertTo-NotionDateTime $date (ConvertTo-WorklogMinutes $entry.to) $config.notion.dateTimeFormat
		$row[$columns.task] = if ($entry.task) { $entry.task } else { $Task }
		$row[$columns.filled] = $config.notion.noValue
		$row[$columns.autoGenerated] = $config.notion.yesValue
		[pscustomobject]$row
	}
	$rows | Export-Csv -LiteralPath $OutPath -NoTypeInformation -Encoding UTF8

	Write-Output ("CSV: {0} записів, {1} год -> {2}" -f $entries.Count, ($entries | Measure-Object -Property hours -Sum).Sum, $OutPath)
}


function New-WorklogDateProbe
{
	<#
	.SYNOPSIS
	Пробний CSV для підбору формату дати-часу, який розпізнає імпорт Notion.
	.DESCRIPTION
	Один рядок на кожен формат-кандидат: у Description - сам формат, дата-час - той самий
	момент. Після імпорту в Notion видно, у яких рядках "Start time" заповнився; такий формат
	записати в config.notion.dateTimeFormat, а пробні рядки видалити.
	#>
	param(
		[datetime]$Start = (Get-Date).Date.AddHours(9),
		[string]$Task = '',
		[string]$OutPath
	)

	$config = Get-WorklogConfig
	$columns = $config.notion.columns
	$formats = 'MMMM d, yyyy h:mm tt', 'yyyy-MM-dd HH:mm', 'yyyy-MM-ddTHH:mm:ss', 'yyyy/MM/dd HH:mm',
		'MM/dd/yyyy h:mm tt', 'dd/MM/yyyy H:mm', 'dd.MM.yyyy HH:mm'
	if (-not $OutPath)
	{
		$OutPath = Join-Path $config.workDir 'Notion - перевірка формату дати.csv'
	}

	$rows = foreach ($format in $formats)
	{
		$row = [ordered]@{}
		$row[$columns.text] = "PROBE $format"
		$row[$columns.start] = $Start.ToString($format, $script:Invariant)
		$row[$columns.end] = $Start.AddMinutes(30).ToString($format, $script:Invariant)
		$row[$columns.task] = $Task
		$row[$columns.filled] = $config.notion.noValue
		$row[$columns.autoGenerated] = $config.notion.yesValue
		[pscustomobject]$row
	}
	$rows | Export-Csv -LiteralPath $OutPath -NoTypeInformation -Encoding UTF8

	Write-Output ("Пробний CSV: {0} форматів -> {1}" -f $formats.Count, $OutPath)
	$rows | Format-Table -AutoSize | Out-String -Width 250
}


function Show-WorklogEntries
{
	<#
	.SYNOPSIS
	Короткий перелік записів: дата, з-до, години, текст.
	#>
	param(
		[Parameter(Mandatory)] [string]$Path,
		[string]$TaskCode
	)

	Import-WorklogEntries -Path $Path -TaskCode $TaskCode | Format-Table date, from, to, hours, auto, text -AutoSize -Wrap | Out-String -Width 250
}

function New-WorklogNotionOps
{
	<#
	.SYNOPSIS
	Готова програма змін для Notion: які плейсхолдери переписати, а які записи створити.
	.DESCRIPTION
	Заповнена сітка лягає на інтервали плану. Перший запис, що потрапив в інтервал
	плейсхолдера, переписує його сторінку (update), решта створюються поруч (create) -
	так ручні записи не дублюються, а зникає лише їхній текст-заглушка.
	Операції лише формуються; виконує їх Claude інструментами конектора Notion, звіряючи
	перелік із користувачем. Видалення не формується ніколи: плейсхолдер, якому не дісталось
	жодного запису, потрапляє в операцію kind = "залишок" - його користувач прибирає сам.
	.PARAMETER TaskPage
	Сторінка задачі для нових записів, якщо в плані її немає (ідентифікатор або посилання).
	#>
	param(
		[Parameter(Mandatory)] [string]$Path,
		[Parameter(Mandatory)] [string]$PlanPath,
		[string]$TaskPage = '',
		[string]$OutPath
	)

	$config = Get-WorklogConfig
	$entries = @(Import-WorklogEntries -Path $Path | Sort-Object date, from)
	$plan = @(Read-WorklogJson $PlanPath)
	$ops = New-Object System.Collections.Generic.List[object]
	$taken = @{}

	foreach ($item in $plan)
	{
		$page = Get-OptionalValue $item 'page'
		if (-not $page)
		{
			continue
		}

		$date = (ConvertTo-WorklogDate $item.date).ToString('yyyy-MM-dd', $script:Invariant)
		$from = ConvertTo-WorklogMinutes $item.from
		$to = ConvertTo-WorklogMinutes $item.to
		$itemTask = Get-OptionalValue $item 'taskPage'
		if (-not $itemTask)
		{
			$itemTask = $TaskPage
		}

		$inside = @($entries | Where-Object {
			-not $taken.ContainsKey($_.page + $_.date + $_.from) -and $_.date -eq $date -and
			(ConvertTo-WorklogMinutes $_.from) -ge $from -and (ConvertTo-WorklogMinutes $_.to) -le $to
		})
		$first = $true
		foreach ($entry in $inside)
		{
			$taken[$entry.page + $entry.date + $entry.from] = $true
			$ops.Add((New-WorklogNotionOp -Entry $entry -Config $config -TaskPage $itemTask `
				-Kind $(if ($first) { 'update' } else { 'create' }) -Page $(if ($first) { $page } else { '' }) `
				-Was $(if ($first) { Get-OptionalValue $item 'text' } else { '' })))
			$first = $false
		}

		if ($first)
		{
			$ops.Add([pscustomobject]@{
				kind = 'залишок'; page = $page; date = $date
				from = $item.from; to = $item.to
				text = ''; was = (Get-OptionalValue $item 'text'); properties = $null
			})
		}
	}

	foreach ($entry in $entries)
	{
		if (-not $taken.ContainsKey($entry.page + $entry.date + $entry.from))
		{
			$page = if ($entry.page) { $entry.page } else { '' }
			$kind = if ($page) { 'update' } else { 'create' }
			$task = if ($entry.taskPage) { $entry.taskPage } else { $TaskPage }
			$ops.Add((New-WorklogNotionOp -Entry $entry -Config $config -TaskPage $task -Kind $kind -Page $page -Was ''))
		}
	}

	if (-not $OutPath)
	{
		$OutPath = [System.IO.Path]::ChangeExtension($Path, '.ops.json')
	}
	ConvertTo-Json -InputObject ([object[]]$ops.ToArray()) -Depth 4 | Set-Content -LiteralPath $OutPath -Encoding UTF8

	$counts = @($ops | Group-Object kind | ForEach-Object { '{0}: {1}' -f $_.Name, $_.Count }) -join ', '
	Write-Output ("Операції ({0}) -> {1}" -f $counts, $OutPath)
	$ops | Format-Table kind, date, from, to, was, text -AutoSize -Wrap | Out-String -Width 220
}


function New-WorklogNotionOp($Entry, $Config, [string]$TaskPage, [string]$Kind, [string]$Page, [string]$Was)
{
	<#
	.SYNOPSIS
	Одна операція: властивості сторінки Timesheet у тому вигляді, який приймає конектор Notion.
	.DESCRIPTION
	Сітка й увесь модуль працюють у місцевому часі журналу, а конектор приймає UTC - тож час
	переводиться поясом notion.mcpTimeZoneId (ConvertTo-NotionRowDate). FilledInIta не
	чіпається на update - прапорець перенесення в ITA ставить сам користувач.
	#>
	$columns = $Config.notion.columns
	$date = ConvertTo-WorklogDate $Entry.date

	$properties = [ordered]@{}
	$properties[$columns.text] = $Entry.text
	$properties["date:$($columns.start):start"] = ConvertTo-NotionRowDate $date.AddMinutes((ConvertTo-WorklogMinutes $Entry.from)) $Config
	$properties["date:$($columns.start):is_datetime"] = 1
	$properties["date:$($columns.end):start"] = ConvertTo-NotionRowDate $date.AddMinutes((ConvertTo-WorklogMinutes $Entry.to)) $Config
	$properties["date:$($columns.end):is_datetime"] = 1
	if ($TaskPage)
	{
		$properties[$columns.task] = @($TaskPage)
	}
	$properties[$columns.autoGenerated] = $Config.notion.mcpYesValue
	if ($Kind -eq 'create')
	{
		$properties[$columns.filled] = $Config.notion.mcpNoValue
	}

	return [pscustomobject]@{
		kind = $Kind
		page = $Page
		date = $Entry.date
		from = $Entry.from
		to   = $Entry.to
		text = $Entry.text
		was  = $Was
		properties = $properties
	}
}

#endregion


Export-ModuleMember -Function Get-WorklogConfig, Import-WorklogEntries, ConvertFrom-NotionRows, Get-WorklogPlaceholders,
	New-WorklogPlan, New-WorklogGrid, Test-WorklogEntries, New-WorklogNotionOps, Export-WorklogCsv, New-WorklogDateProbe,
	Show-WorklogEntries
